name: parcel-drupal-example
recipe: drupal9
config:
  composer_version: '2.0.7'
  webroot: ./web
tooling:
  npm:
    service: node
    cmd: "npm"
    dir: /app/web/themes/custom/parcelexample
    description: "Runs npm for installing, removing modules or running scripts. Ex: lando npm <yourcommand>"
services:
  node:
    type: node:14
    build:
      - "cd /app/web/themes/custom/parcelexample && npm install && npm run build"
  appserver:
    build:
      - composer install
